WITH cte1 AS (SELECT TIV_2015 FROM insurance GROUP BY TIV_2015 HAVING COUNT(TIV_2015) > 1),
cte2 AS (SELECT pos FROM (SELECT CONCAT(LAT, '-', LON) AS pos FROM insurance) AS t GROUP BY pos HAVING COUNT(pos) = 1)
SELECT SUM(TIV_2016) AS TIV_2016 FROM insurance WHERE TIV_2015 in (SELECT * FROM cte1) AND CONCAT(LAT, '-', LON) IN (SELECT * FROM cte2)

